#define HAP_SDK_VER "4.0"
#define MFI_VER HAP_SDK_VER "-040b0f3"

#define CONFIG_HAP_HTTP_STACK_SIZE 12288
#define CONFIG_HAP_HTTP_SERVER_PORT 8080
#define CONFIG_HAP_HTTP_CONTROL_PORT 32859
#define CONFIG_HAP_HTTP_MAX_OPEN_SOCKETS 6
#define CONFIG_HAP_HTTP_MAX_URI_HANDLERS 16

#define CONFIG_IC2_SPEED 400000
#define CONFIG_SDA_GPIO 26
#define CONFIG_SCL_GPIO 27
#define CONFIG_I2C_MAX_READ_COUNT 150
#define CONFIG_I2C_RETRY_COUNT 200